# From the Numpy Documentation

https://numpy.org/doc/stable/user/quickstart

In [ ]:
import numpy as np

In [ ]:
list(range(1, 16, 3))

In [ ]:
x = np.arange(1, 10, 2)

In [21]:
x.dtype

dtype('int32')

In [23]:
x

array([1, 3, 5, 7, 9])

In [24]:
x.shape

(5,)

In [19]:
y = np.arange(1.5, 10.1, 0.02)

In [20]:
y.dtype

dtype('float64')

In [26]:
a = np.arange(15).reshape(3, 5)

In [ ]:
a

In [27]:
a.shape

(3, 5)

In [28]:
y.shape

(430,)

In [30]:
x.reshape(-1,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [34]:
x = np.arange(0.0, 10.0, 0.01)
x

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [35]:
y = x ** 2
y

array([0.00000e+00, 1.00000e-04, 4.00000e-04, 9.00000e-04, 1.60000e-03,
       2.50000e-03, 3.60000e-03, 4.90000e-03, 6.40000e-03, 8.10000e-03,
       1.00000e-02, 1.21000e-02, 1.44000e-02, 1.69000e-02, 1.96000e-02,
       2.25000e-02, 2.56000e-02, 2.89000e-02, 3.24000e-02, 3.61000e-02,
       4.00000e-02, 4.41000e-02, 4.84000e-02, 5.29000e-02, 5.76000e-02,
       6.25000e-02, 6.76000e-02, 7.29000e-02, 7.84000e-02, 8.41000e-02,
       9.00000e-02, 9.61000e-02, 1.02400e-01, 1.08900e-01, 1.15600e-01,
       1.22500e-01, 1.29600e-01, 1.36900e-01, 1.44400e-01, 1.52100e-01,
       1.60000e-01, 1.68100e-01, 1.76400e-01, 1.84900e-01, 1.93600e-01,
       2.02500e-01, 2.11600e-01, 2.20900e-01, 2.30400e-01, 2.40100e-01,
       2.50000e-01, 2.60100e-01, 2.70400e-01, 2.80900e-01, 2.91600e-01,
       3.02500e-01, 3.13600e-01, 3.24900e-01, 3.36400e-01, 3.48100e-01,
       3.60000e-01, 3.72100e-01, 3.84400e-01, 3.96900e-01, 4.09600e-01,
       4.22500e-01, 4.35600e-01, 4.48900e-01, 4.62400e-01, 4.761

In [37]:
np.linspace(0.0,10.0,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [38]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
I = np.eye(3)

In [42]:
I.dtype

dtype('float64')

In [43]:
I.astype('int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [46]:
I[:, 1]

array([0., 1., 0.])

In [48]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
b.sum(axis=0) 

array([12, 15, 18, 21])

In [50]:
b.min(axis=1) 

array([0, 4, 8])

In [51]:
b.cumsum(axis=1) 

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [53]:
c = a.view()
c is a

False

In [54]:
c.base is a

False

***

## End